"""Add favorite_genres and favorite_actors

Revision ID: 4616bd5a1ca9
Revises: df17c3fb040a
Create Date: 2025-03-29 08:11:07.723266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4616bd5a1ca9'
down_revision: Union[str, None] = 'df17c3fb040a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('favorite_actors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('favorite_directors', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_directors')
    op.drop_column('users', 'favorite_actors')
    op.drop_column('users', 'favorite_genres')
    # ### end Alembic commands ###
