"""add preferred_language to users

Revision ID: c36a3467804f
Revises: ca4bbd565b8c
Create Date: 2026-08-24 10:54:16.353769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36a3467804f'
down_revision: Union[str, None] = 'ca4bbd565b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=True))
    op.drop_index('ix_wishlists_user', table_name='wishlists')
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.create_index('ix_wishlists_user', 'wishlists', ['user_id'], unique=False)
    op.drop_column('users', 'preferred_language')
    # ### end Alembic commands ###
