""" Add extended preferences

Revision ID: cad864e59f0d
Revises: c36a3467804f
Create Date: 2026-08-24 12:13:03.924685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad864e59f0d'
down_revision: Union[str, None] = 'c36a3467804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_content_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_regional_languages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('preferred_movie_genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('preferred_series_genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('preferred_release_era', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_release_era')
    op.drop_column('users', 'preferred_series_genres')
    op.drop_column('users', 'preferred_movie_genres')
    op.drop_column('users', 'preferred_regional_languages')
    op.drop_column('users', 'preferred_content_type')
    # ### end Alembic commands ###
