"""add_profile_pictures

Revision ID: d271924f9321
Revises: fb5a64e19722
Create Date: 2026-09-22 22:21:02.639404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd271924f9321'
down_revision: Union[str, None] = 'fb5a64e19722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_profile_picture_url')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
