"""Add tmdb_id to Movie table

Revision ID: df17c3fb040a
Revises: 621ed384b1d6
Create Date: 2025-03-28 06:13:54.818252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df17c3fb040a'
down_revision: Union[str, None] = '621ed384b1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'movies', ['tmdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'tmdb_id')
    # ### end Alembic commands ###
