"""Add Google OAuth fields and OAuthExchangeCode

Revision ID: fb5a64e19722
Revises: 976689cfdf4f
Create Date: 2026-09-22 20:24:00.879096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a64e19722'
down_revision: Union[str, None] = '976689cfdf4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_exchange_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_exchange_codes_code'), 'oauth_exchange_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oauth_exchange_codes_id'), 'oauth_exchange_codes', ['id'], unique=False)
    op.add_column('users', sa.Column('auth_provider', sa.String(), server_default='local', nullable=False))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
    op.drop_index(op.f('ix_oauth_exchange_codes_id'), table_name='oauth_exchange_codes')
    op.drop_index(op.f('ix_oauth_exchange_codes_code'), table_name='oauth_exchange_codes')
    op.drop_table('oauth_exchange_codes')
    # ### end Alembic commands ###
